USE [master]
GO

/****** Object:  Database [Shirokov_Autoservice]    Script Date: 24.11.2021 18:47:58 ******/
CREATE DATABASE [Shirokov_Autoservice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shirokov_Autoservice', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Shirokov_Autoservice.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Shirokov_Autoservice_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Shirokov_Autoservice_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shirokov_Autoservice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Shirokov_Autoservice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET ARITHABORT OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Shirokov_Autoservice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Shirokov_Autoservice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Shirokov_Autoservice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Shirokov_Autoservice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Shirokov_Autoservice] SET  MULTI_USER 
GO

ALTER DATABASE [Shirokov_Autoservice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Shirokov_Autoservice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Shirokov_Autoservice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Shirokov_Autoservice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Shirokov_Autoservice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Shirokov_Autoservice] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Shirokov_Autoservice] SET  READ_WRITE 
GO

